<?php

########################################################################
# Extension Manager/Repository config file for ext: "mootools_essentials"
#
# Auto generated by Extension Builder 2012-04-02
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MooTools Essentials',
	'description' => 'Ready to use MooTools Behaviors - use advanced effects by just setting html5 tag data-behavior=\"...\"',
	'category' => 'plugin',
	'author' => 'Thomas Allmer',
	'author_email' => 'thomas.allmer@webteam.at',
	'author_company' => 'WEBTEAM GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>