<?php
return array(
	'BE' => array(
		'disable_exec_function' => 0,
	),
	'EXT' => array(
		'extConf' => array(
			'em' => 'a:1:{s:17:"selectedLanguages";s:2:"de";}',
			'extbase' => 'a:0:{}',
			'fluid' => 'a:0:{}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'tinymce_rte' => 'a:2:{s:10:"loadConfig";s:34:"EXT:tinymce_rte/static/standard.ts";s:18:"pageLoadConfigFile";s:34:"EXT:tinymce_rte/static/pageLoad.ts";}',
		),
		'extListArray' => array(
			'extbase',
			'info',
			'perm',
			'func',
			'filelist',
			'about',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
			'fluid',
			'tinymce_rte',
			'site_default',
			'cshmanual',
			'opendocs',
			'recycler',
			'scheduler',
			'workspaces',
			'mootools_stack',
			'mootools_essentials',
			'gridelements',
		),
		'extList_FE' => 'extbase,version,install,t3skin,felogin,form,fluid,tinymce_rte,site_default,workspaces,mootools_stack,mootools_essentials,gridelements',
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(),
		),
	),
	'GFX' => array(
		'gdlib_png' => 1,
		'im' => 0,
		'im_combine_filename' => '',
		'im_path' => '',
		'im_path_lzw' => '',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
			'tx_coreupdates_installnewsysexts' => '1',
			'tx_coreupdates_installsysexts' => '1',
		),
	),
	'SYS' => array(
		'compat_version' => '6.0',
		'encryptionKey' => '109e0c8d057cdec2b5d220756a0cd8cde90e91737d41518eeb8da1c77e5c8845fb948eb1ad9dbc325a609a714a452f95',
		'sitename' => 'fDummy',
	),
);
?>